# Generated by Django 2.2.14 on 2022-09-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='trending',
            field=models.BooleanField(default=False, help_text='0=default, 1=Trending'),
        ),
    ]
