# Generated by Django 2.2.14 on 2022-09-15 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact_number',
            field=models.TextField(default=django.utils.timezone.now, max_length=14),
            preserve_default=False,
        ),
    ]
