# Generated by Django 2.2.14 on 2022-09-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_address_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact_number',
            field=models.CharField(max_length=14),
        ),
    ]
